live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.95
startup_mode = "FullScreen"

[window.padding]
x = 5
y = 0

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[[colors.indexed_colors]]
color = "0xff8f40"
index = 16

[[colors.indexed_colors]]
color = "0xe6b673"
index = 17

[[colors.indexed_colors]]
color = "0x131721"
index = 18

[[colors.indexed_colors]]
color = "0x272d38"
index = 19

[[colors.indexed_colors]]
color = "0xbfbdb6"
index = 20

[[colors.indexed_colors]]
color = "0xe6e1cf"
index = 21

[colors.bright]
black   = '0x6e7681'
red     = '0xfdac54'
green   = '0x79c0ff'
yellow  = '0xe3b341'
blue    = '0x79c0ff'
magenta = '0xbc8cff'
cyan    = '0x39c5cf'
white   = '0xb1bac4'

[colors.cursor]
cursor = "0xc9d1d9"
text = "0x0d1117"

[colors.normal]
black   = '0x484f58'
red     = '0xec8e2c'
green   = '0x58a6ff'
yellow  = '0xd29922'
blue    = '0x58a6ff'
magenta = '0xbc8cff'
cyan    = '0x39c5cf'
white   = '0xb1bac4'

[colors.primary]
background = "0x0d1117"
foreground = "0xe6e1cf"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"
