#!/usr/bin/env sh

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config external_bar                 all:24:0
yabai -m config mouse_follows_focus          on 
yabai -m config window_placement             second_child
yabai -m config window_opacity               on 
yabai -m config window_topmost               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                float
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off 
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config focus_follows_mouse          off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15 
yabai -m config window_gap                   15

setup_space 1 term
setup_space 2 browser
setup_space 3 postman
setup_space 4 slack
setup_space 5 other

yabai -m rule --add app="^Alacritty$" space=1
yabai -m rule --add app="^Brave Browser$" space=2
yabai -m rule --add app="^Postman$" space=3
yabai -m rule --add app="^Slack$" space=4
yabai -m rule --add app="^Mongo$" space=4

# rules
## makes system preferences always floating
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^Pulse Secure$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Calculator$" manage=off

# Auto focus on window after closed window
yabai -m signal --add event=window_destroyed action="yabai -m window --focus mouse"
yabai -m signal --add event=window_minimized action="yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m window --focus mouse"

# signals
## updates workspace widget when space changes
yabai -m signal --add event=space_changed \
  action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"pecan-workspace-jsx\"'"


echo "yabai configuration loaded and ready.."
