#!/bin/zsh

selected_dir=$(fd --full-path $TMUX_F_DIR --type d --exclude .git | fzf --border rounded --ansi)
if [ -z "$selected_dir" ]; then
    exit 1
fi

session_name=$(basename $selected_dir)

tmux new-session -c $selected_dir -s $session_name
